name: Update Formula
run-name: Update ${{ github.event.client_payload.binary }} to ${{ github.event.client_payload.version }}

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{ toJson(github.event.client_payload) }}

    steps:
      - uses: actions/checkout@v4

      - uses: archetect/render-action@v1
        with:
          source: "archetype" 
          answers: $PAYLOAD

      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update ${{ github.event.client_payload.binary }} to ${{ github.event.client_payload.version }}"
          git push
